name: RankViewer
main: me.engineersbox.rankviewer.Main
version: 1.15
author: EngineersBox
commands:
    rv:
        description: Displays Plugin Version Information
        usage: /rv
        permission: rv.use
    rv version:
        description: Displays Plugin Version Information
        usage: /rv version
        permission: rv.version
    rv help:
        description: Displays Plugin Help Information
        usage: /rv help
        permission: rv.help
    rv reload:
        description: Reloads The Plugin
        usage: /rv reload
        permission: rv.reload
permissions:
    rv.*:
        description: Gives Access To All RankViewer Permissions
        children:
        rv.version: true
        rv.help: true
        rv.reload: true
        rv.use: true
        rv.discord: true
    rv.version:
        description: Gives Access To View Current Plugin Version
        default: true
    rv.help:
        description: Gives Access To RankViewer Help Section
        default: true
    rv.reload:
        description: Gives Access To Reload The Pugin
        default: false
    rv.use:
        description: Alias for rv.help
        default: true
    rv.discord:
        description: Allow Messages To Be Sent To Discord Channel Target
        default: true